[package]
name = "rustmiko"
description = "A Netmiko rewrite for Rust"
authors = ["Kek5chen"]
version = "0.2.2"
edition = "2021"
license = "MIT"
repository = "https://github.com/Kek5chen/rustmiko"

[dependencies]
russh = "0.46.0-beta.3"
telnet = "0.2.1"
anyhow = "1.0.86"
log = "0.4.22"